webdriver.driver=chrome
webdriver.base.url=http://localhost:3000
serenity.project.name=AUTO_FRONT_SCREENPLAY
thucydides.project.name=AUTO_FRONT_SCREENPLAY
serenity.take.screenshots=AFTER_EACH_STEP
headless.mode=false