#
#Mon Mar 30 14:45:51 ECT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, --test-type, --no-sandbox, \\r\\n  --ignore-certificate-errors, --disable-popup-blocking, \\r\\n  --disable-default-apps, --disable-extensions-file-access-check, \\r\\n  --incognito, --disable-infobars, --disable-gpu], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
